# ~/.tmux.conf

set -g default-terminal "screen-256color"
# set -g status-style bg=default,fg="#839496"
set -g status-style bg=default,fg="#839496"
set -g status-left-length 120
set -g status-right-length 120
set -g window-style 'fg=#839496,bg=default'
set -g window-active-style 'fg=#839496,bg=default'
set -g window-active-style 'fg=#839496,bg=default'
set-option -g status-position top


set -g status-bg default
set -g status-fg "#839496"
set -g status-right "#{pane_current_path}"

unbind C-b
set -g prefix C-a
bind C-a send-prefix


setw -g mode-keys vi
bind S command-prompt -p "New Session:" "new-session -A -s '%%'"
bind K confirm kill-session
bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux config reloaded"
bind v copy-mode
bind -T copy-mode-vi J send-keys -X cursor-down 10
bind -T copy-mode-vi K send-keys -X cursor-up 10
